trigger:
- dev
- qa
- stage

resources:
- repo: self

variables:
  branchName: $(Build.SourceBranchName)
  ARMServiceConnection: kuber-deployment
  imageRepository: mycontainerwest.azurecr.io/firstapi-$(branchName)
  containerRegistry: mycontainerwest
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  kubernetesCluster: myclusterwest
  keyVault: mykeyvaultwestt
  resourceGroup: MyGroup
  tag: $(Build.BuildId)

  vmImageName: ubuntu-latest

stages:
- stage: Deploy
  displayName: Build and Deploy
  jobs:  
  - job: Deploy
    displayName: Build and Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: DockerInstaller@0
        displayName: Installing Docker...
        inputs:
          dockerVersion: 19.03.10
      - task: AzureCLI@2
        displayName: Logging in to ACR...
        inputs:
          azureSubscription: $(ARMServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az acr login -n $(containerRegistry)
      - task: Docker@2
        displayName: Build and push image...
        inputs:
          repository: $(imageRepository)
          command: buildAndPush
          Dockerfile: $(dockerfilePath)
          tags: v2
      - task: AzureCLI@2
        displayName: Getting Env veriables...
        inputs:
          azureSubscription: $(ARMServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            sed -i "s/{{image-name}}/$(imageRepository)/g" ./firstapi-chart/values.yaml
            sed -i "s/{{db-host}}/`az keyvault secret show --name db-host --vault-name $(keyVault) --query value | base64`/g; \
            	 s/{{db-name}}/`az keyvault secret show --name db-name --vault-name $(keyVault) --query value | base64`/g; \
            	 s/{{db-password}}/`az keyvault secret show --name db-password --vault-name $(keyVault) --query value | base64`/g" ./firstapi-chart/firstapi-secret.yaml
      - task: Kubernetes@1
        displayName: Setting Env veriables...
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: $(ARMServiceConnection)
          azureResourceGroup: $(resourceGroup)
          kubernetesCluster: $(kubernetesCluster)
          command: apply
          arguments: -f ./firstapi-chart/firstapi-secret.yaml
      - task: HelmInstaller@1
        displayName: Installing helm...
        inputs:
          helmVersionToInstall: latest
      - task: AzureCLI@2
        displayName: Deploying the service to kubernete...
        inputs:
          azureSubscription: $(ARMServiceConnection)
          scriptType: bash
          workingDirectory: $(Build.SourcesDirectory)/firstapi-chart
          scriptLocation: inlineScript
          inlineScript: |
            az aks get-credentials --resource-group=$(resourceGroup) --name=$(kubernetesCluster)
            helm upgrade --install firstapi . -f ./values.yaml
