trigger:
- master

resources:
- repo: self

variables:
  ARMServiceConnection: kuber-deployment
  imageRepository: firstapi
  containerRegistry: mynewcrg.azurecr.io
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  tag: $(Build.BuildId)

  vmImageName: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: DockerInstaller@0
        displayName: Installing Docker...
        inputs:
          dockerVersion: 19.03.10
      - task: AzureCLI@2
        displayName: Logging in to Azure...
        inputs:
          azureSubscription: $(ARMServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az acr login -n mycontainerwest
      - task: Docker@2
        displayName: Build and push image...
        inputs:
          repository: mycontainerwest.azurecr.io/firstapi
          command: buildAndPush
          Dockerfile: $(Build.SourcesDirectory)/Dockerfile
          tags: v1
      - task: AzureCLI@2
        displayName: Set Environments variables
        inputs:
          azureSubscription: $(ARMServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            sed "s/{{db-host}}/`az keyvault secret show --name db-host --vault-name mykeyvaultwest --query value | base64`/g; \
            	 s/{{db-name}}/`az keyvault secret show --name db-name --vault-name mykeyvaultwest --query value | base64`/g; \
            	 s/{{db-password}}/`az keyvault secret show --name db-password --vault-name mykeyvaultwest --query value | base64`/g" ./firstapi-chart/firstapi-secret.yaml.tmpl > ./firstapi-chart/firstapi-secret.yaml
            cat ./firstapi-chart/firstapi-secret.yaml
      - task: Kubernetes@1
        displayName: kubectl apply using arguments
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: $(ARMServiceConnection)
          azureResourceGroup: MyGroup
          kubernetesCluster: myclusterwest
          command: apply
          arguments: -f ./firstapi-chart/firstapi-secret.yaml
      - task: HelmInstaller@1
        displayName: Installing helm...
        inputs:
          helmVersionToInstall: latest
      - task: AzureCLI@2
        displayName: Deploy the service to kubernetes
        inputs:
          azureSubscription: $(ARMServiceConnection)
          scriptType: bash
          workingDirectory: $(Build.SourcesDirectory)/firstapi-chart
          scriptLocation: inlineScript
          inlineScript: |
            az aks get-credentials --resource-group=MyGroup --name=myclusterwest
            helm upgrade --install firstapi . -f ./values.yaml
