apiVersion: v1
kind: Service
metadata:
  name: firstapi-external-service
spec:
  selector:
    app: firstapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000