apiVersion: v1
kind: Namespace
metadata:
  name: my-space
---
apiVersion: v1
kind: Secret
metadata:
  name: firstapi-secret
  namespace: my-space
type: Opaque
data:
  db-host: {{db-host}}
  db-name: {{db-name}}
  db-password: {{db-password}}